### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by JanMoritzP** [JanMoritzP/schedule-your-meeting#5]
- [x] Add in user selection in the meeting page
- [x] Add in the backend data collection for the timedata described in #4 
- [x] Add in the algorithm to determine the best timeslot by adding the timedata and determining the best sum with weights for the priorities.

**Comment by JanMoritzP** [comment]
- [ ] Add in a tooltip for the meeting length (You have to have a meeting be at least 15 minutes long and the minutes have to be divisible by 15, so 1h30 would be possible or 45 minutes

**Comment by JanMoritzP** [comment]
- [x] Add expiration to documents. One week should do just fine(604800 seconds)

**Comment by JanMoritzP** [comment]
- [x] Add in priority to meetingFinder
- [x] Add in warnings in the frontend for the meetingCreation

**Comment by JanMoritzP** [comment]
- [x] Think about the <select> tag in some of the inputs

**Comment by JanMoritzP** [comment]
- [x] Style the page

**Comment by JanMoritzP** [comment]
> * [x]  Add expiration to documents. One week should do just fine(604800 seconds)

I went with two weeks for now

**Comment by JanMoritzP** [comment]
- [x] Create home button in meeting
- [x] Create a better meeting creation button
- [x] Work out the best meetings screen

**Comment by JanMoritzP** [comment]
- [ ] Add a button on the homescreen to join a meeting (Already with input field and stuff

**Comment by JanMoritzP** [comment]
- [x] Fix the 'painting' system to not go by `selected` but by `[perfect, works, ratherNot]`

**Comment by JanMoritzP** [comment]
- [x] Make it so, that when the end time goes before the or equal to the start time, it resets

**Comment by JanMoritzP** [comment]
- [x] Rework the meeting finder, issue is, that allAvailable might not be zero, but the timeslot might be too small, then nothing useful would be transmitted
